# 
control_dt: 0.02

msg_type: "go"     # "hg" or "go"
imu_type: "pelvis"    # "torso" or "pelvis"
  
lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

policy_path: "/home/mmj/sim2real_g2w/unitree_rl_gym/deploy/pre_train/g2w/only_x_10000.pt"

joint2motor_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

kps: [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 0, 0, 0, 0]
kds: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0.5, 0.5, 0.5, 0.5]

default_real_angles: [0.0, 0.67, -1.3, 0.0, 0.67, -1.3, 0.0, 0.67, -1.3, 0.0, 0.67, -1.3, 0.0, 0.0, 0.0, 0.0]
default_sim_angles: [0.0, 0.67, -1.3, 0.0, 0.0, 0.67, -1.3, 0.0, 0.0, 0.67, -1.3, 0.0, 0.0, 0.67, -1.3, 0.0]

lin_vel_scale: 2.0
ang_vel_scale: 0.25
cmd_scale: [2, 2, 0.25]
dof_err_scale: 1.0
dof_vel_scale: 0.05

action_scale: 0.25

num_actions: 16
num_obs: 73

wheel_real_indices: [12, 13, 14, 15]
wheel_sim_indices: [3, 7, 11, 15]
wheel_speed: 1